from common import *

ROUTES = [
  # ───────────── Kakheti ─────────────
  {
    "slug": "black-rock-lake",
    "name": "ლაგოდეხი – შავი კლდეების ტბა",
    "name_en": "Lagodekhi – Black Rock Lake",
    "region_id": "kakheti",
    "difficulty": "hard",
    "days_min": 2, "days_max": 3,
    "distance_km": 38, "elevation_gain_m": 2890, "elevation_loss_m": 2890,
    "max_altitude_m": 2860, "min_altitude_m": 570,
    "route_type": "loop",
    "season_months": [6, 7, 8, 9],
    "tags": ["lakes", "forest", "wildlife", "huts", "national_park", "border_zone"],
    "featured": True,
    "summary": "ლაგოდეხის ეროვნული პარკის ცნობილი ტრეკი: კოლხური ტყიდან ალპურ ზონამდე, შავი კლდეების ტბამდე დაღესტნის საზღვარზე.",
    "description": (
      "ლაგოდეხის ვიზიტორთა ცენტრიდან (~570 მ) პირველ დღეს ტყით ~1 500 მ ადიხარ მეტეოს თავშესაფრამდე. მეორე დღეს ალპური მდელოებით, ქედზე "
      "შავი კლდეების ტბამდე (~2 850 მ) მიდიხარ — ტბა საქართველო–რუსეთის (დაღესტნის) საზღვარზეა. "
      "ღამე დემიდოვოს თავშესაფარში, მესამე დღეს კი ~2 100 მ დაღმართით ლაგოდეხში ბრუნდები. ტყეში ირემი, არჩვი და ჯიხვია."
    ),
    "difficulty_notes": "პირველ დღეს ~1 500 მ განუწყვეტელი აღმართია, ბოლო დღეს — ~2 100 მ დაღმართი. ფიზიკურად ძალიან დამღლელი, თუმცა ტექნიკური ადგილები არ არის.",
    "getting_there": "ლაგოდეხამდე თბილისიდან მარშრუტკა ისნის სადგურიდან (~2.5 სთ; 2026 წლის მონაცემით ~15 ლარი, დილიდან საღამომდე). ვიზიტორთა ცენტრი ქალაქშია.",
    "accommodation": "მეტეოს და დემიდოვოს თავშესაფრები (საწოლებით; 2026 წლის მონაცემით ~30 ლარი ღამე) ან კარვის ადგილი (~5 ლარი).",
    "water": "თავშესაფრებთან და მონიშნულ წყაროებთან. ზაფხულის ბოლოს ზოგი წყარო შრება.",
    "permits": "გასვლამდე დარეგისტრირდი ლაგოდეხის დაცული ტერიტორიების ადმინისტრაციაში. ტბასთან სასაზღვრო პოსტია — პასპორტი ან პირადობა აუცილებელია.",
    "dangers": "წვიმის შემდეგ ტყის ბილიკი ძალიან მოლიპულია. ~910 მ სიმაღლეზე ბილიკები იყოფა — რუკას დახედე. ზემოთ ნისლი და სიცივე.",
    "mobile_coverage": "ქვედა ნაწილში არის, ზემოთ — სუსტი.",
    "gear": MULTI_GUESTHOUSE + [SLEEPING_BAG, FOOD_DAYS, ID],
    "tips": [
      "ძლიერი მოლაშქრეები ორ დღეში ასრულებენ, მაგრამ სამი დღე ბევრად სასიამოვნოა.",
      "თავშესაფარში ადგილი წინასწარ დაჯავშნე ადმინისტრაციის გავლით.",
    ],
    "sources": "https://www.caucasus-trekking.com/treks/trek-to-the-black-rock-lake ; https://apa.gov.ge/en/eco-tourism/Trails/lagodexis-daculi-teritoriebis-turistuli-bilikebi/4-shvi-kldeebis-tba",
    "stops": [
      stop("ლაგოდეხის ვიზიტორთა ცენტრი", "start", 41.8323, 46.2829, day=1, alt=570, desc="რეგისტრაცია და ინფორმაცია.", en="Lagodekhi visitor center"),
      stop("მეტეოს თავშესაფარი", "hut", 41.8852, 46.2900, day=1, alt=1950, night=True, en="Meteo shelter"),
      stop("შავი კლდეების ტბა", "lake", 41.9567, 46.3104, day=2, alt=2850, desc="სასაზღვრო პოსტი — პასპორტის შემოწმება.", en="Black Rock Lake"),
      stop("დემიდოვოს თავშესაფარი", "hut", 41.9047, 46.3242, day=2, alt=2300, night=True, en="Demidovo shelter"),
      stop("ლაგოდეხი", "finish", 41.8323, 46.2829, day=3, alt=570, en="Lagodekhi"),
    ],
  },
  {
    "slug": "ninoskhevi-waterfall",
    "name": "ნინოსხევის ჩანჩქერი (ლაგოდეხი)",
    "name_en": "Ninoskhevi waterfall, Lagodekhi",
    "region_id": "kakheti",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 4,
    "distance_km": 8.5, "elevation_gain_m": 250, "elevation_loss_m": 250,
    "max_altitude_m": 800, "min_altitude_m": 550,
    "route_type": "out_and_back",
    "season_months": [4, 5, 6, 7, 8, 9, 10, 11],
    "tags": ["waterfall", "forest", "family", "national_park", "river_crossing"],
    "summary": "ლაგოდეხის კოლხურ ტყეში ნინოსხევის ხეობით 40-მეტრიან ჩანჩქერამდე — მარტივი და ძალიან ლამაზი ოჯახური ლაშქრობა.",
    "description": (
      "ბილიკი გურგენიანის სადარაჯოდან ტყეში შედის და ნინოსხევის ნაკადულს მიუყვება, რამდენჯერმე გადაკვეთს მას ქვებზე ან პატარა ხიდებზე. "
      "ბოლოს ვიწრო ხეობაში 40 მეტრიანი ჩანჩქერი ჩნდება. ზაფხულის სიცხეში აქ საოცრად გრილა."
    ),
    "difficulty_notes": "მცირე აღმართი, მაგრამ ნაკადულის რამდენჯერმე გადალახვა სველ ქვებზე.",
    "getting_there": "ლაგოდეხამდე თბილისიდან მარშრუტკით ისნის სადგურიდან (~2.5 სთ), იქიდან გურგენიანის სადარაჯომდე ტაქსით (~15 წთ).",
    "water": "ნაკადული გვერდითაა.",
    "permits": "დარეგისტრირდი ლაგოდეხის დაცული ტერიტორიების ადმინისტრაციაში.",
    "dangers": "ძლიერი წვიმის შემდეგ ნაკადულის გადალახვა რთულდება. ქვები მოლიპულია.",
    "mobile_coverage": "ქვედა ნაწილში არის.",
    "gear": DAY_EASY + [SANDALS],
    "tips": ["ფეხსაცმელი, რომელიც არ გეწყინება რომ დასველდეს, ან სანდლები — ბილიკი ბევრჯერ კვეთს ნაკადულს."],
    "sources": "https://georgia.to/trails-of-lagodekhi-protected-areas/",
    "stops": [
      stop("გურგენიანის სადარაჯო", "start", 41.87301, 46.23946, alt=600, desc="ბილიკის დასაწყისი, ზემო გურგენიანთან.", en="Gurgeniani ranger station"),
      stop("ნინოსხევის ჩანჩქერი", "waterfall", 41.8573, 46.2690, alt=800, en="Ninoskhevi waterfall"),
    ],
  },
  {
    "slug": "machi-fortress",
    "name": "მაჭის ციხე (ლაგოდეხი)",
    "name_en": "Machi fortress, Lagodekhi",
    "region_id": "kakheti",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 4,
    "distance_km": 10.5, "elevation_gain_m": 400, "elevation_loss_m": 400,
    "max_altitude_m": 850, "min_altitude_m": 450,
    "route_type": "out_and_back",
    "season_months": [3, 4, 5, 6, 7, 8, 9, 10, 11],
    "tags": ["history", "forest", "national_park"],
    "summary": "ტყიანი ბილიკი შუასაუკუნეების მაჭის ციხემდე — კედლები, საგვარეულო ეკლესია და მიწისქვეშა სავალები ლაგოდეხის ტყეში.",
    "description": "სოფელ მაწიმიდან ბილიკი ტყით ადის მაჭის ციხის ნანგრევებამდე, რომელიც ალაზნის ველს გადაჰყურებს. ციხე კარგად შემორჩენილია: კედლები, კოშკები, ეკლესია.",
    "difficulty_notes": "ზომიერი აღმართი ტყეში.",
    "getting_there": "ბილიკის დასაწყისი სოფელ მაწიმთანაა, ლაგოდეხის ადმინისტრაციიდან ~7 კმ-ში (ტაქსით).",
    "water": "წყალი თან წაიღე.",
    "permits": "დარეგისტრირდი ლაგოდეხის ვიზიტორთა ცენტრში.",
    "dangers": "ციხის კედლებზე ნუ ახვალ — ნანგრევებია.",
    "mobile_coverage": "უმეტესად არის.",
    "gear": DAY_EASY,
    "tips": ["გაზაფხულზე და შემოდგომაზე ყველაზე სასიამოვნოა — ზაფხულში ქვემოთ ცხელა."],
    "sources": "https://georgia.to/trails-of-lagodekhi-protected-areas/",
    "stops": [
      stop("მაჭის ციხის ბილიკის დასაწყისი (მაწიმი)", "start", 41.80935, 46.31026, alt=450, en="Matsimi"),
      stop("მაჭის ციხე", "fortress", 41.8762, 46.2464, alt=850, en="Machi fortress"),
    ],
  },
  {
    "slug": "vashlovani-national-park",
    "name": "ვაშლოვანის ეროვნული პარკი",
    "name_en": "Vashlovani National Park",
    "region_id": "kakheti",
    "difficulty": "moderate",
    "days_min": 2, "days_max": 2,
    "distance_km": 120, "elevation_gain_m": 900, "elevation_loss_m": 900,
    "max_altitude_m": 900, "min_altitude_m": 150,
    "route_type": "loop",
    "season_months": [4, 5, 6, 9, 10, 11],
    "tags": ["4x4", "canyon", "wildlife", "camping", "national_park", "border_zone"],
    "summary": "ნახევრად უდაბნო, ფერადი ხეობები, არწივის ხეობა და ალაზნის ჭალა აზერბაიჯანის საზღვართან — 4x4 მანქანით და მოკლე ლაშქრობებით.",
    "description": (
      "ვაშლოვანი საქართველოს 'სავანაა': მშრალი ღია ტყეები, ტალახის ვულკანები, მიწის 'არეულები' და ღრმა კანიონები. პარკში მოძრაობა მხოლოდ 4x4 მანქანით შეიძლება — "
      "ფეხით მოკლე ლაშქრობები არწივის ხეობასა და სხვა ხეობებში კეთდება. ღამე პარკის კოტეჯებში ან ბანაკში (მაგ. მიჯნისყურე, ალაზნის ჭალა) ათევ."
    ),
    "difficulty_notes": "ფიზიკურად მარტივია, მაგრამ მოშორებული ტერიტორიაა: სიცხე, ცუდი გზები და წყლის ნაკლებობა.",
    "getting_there": "დედოფლისწყარომდე თბილისიდან (~2.5 სთ). პარკში შესვლა მხოლოდ 4x4 მანქანით; ადგილობრივ ჯიპს დედოფლისწყაროში იქირავებ.",
    "accommodation": "პარკის კოტეჯები და ბანაკები (2026 წლის მონაცემით კოტეჯი 40–60 ლარი, კარავი ~5 ლარი ადამიანზე).",
    "water": "პარკში წყალი თითქმის არ არის — ორი დღის მარაგი და საწვავი თან იქონიე.",
    "permits": "დედოფლისწყაროს ვიზიტორთა ცენტრში წინასწარ რეგისტრაცია და პირადობის ასლი აუცილებელია (სასაზღვრო ტერიტორიაა). შესვლის საფასური ~5 ლარი თითო ლოკაციაზე.",
    "dangers": "ზაფხულში (ივლისი–აგვისტო) უკიდურესი სიცხეა. გველები (მათ შორის გიურზა) — ფეხსაცმელი და გრძელი შარვალი. წვიმის შემდეგ თიხის გზები გაუვალი ხდება.",
    "mobile_coverage": "უმეტეს ნაწილში არ არის.",
    "gear": [SHOES_LIGHT, BOOTS, WATER_2, SUN, FIRST_AID, OFFLINE_MAP, CASH, ID, TENT, FOOD_DAYS, HEADLAMP, TRASH, INSECT],
    "tips": [
      "საუკეთესო დრო — აპრილი–მაისი (ყვავილობა) და ოქტომბერი.",
      "ფრინველებზე დასაკვირვებლად აპრილი და ოქტომბერ–ნოემბერია საუკეთესო.",
    ],
    "sources": "https://www.apa.gov.ge/en/eco-tourism/servisebi-da-tarifebi/VashlovaniProtectedAreas",
    "stops": [
      stop("დედოფლისწყაროს ვიზიტორთა ცენტრი", "start", 41.4618, 46.1077, day=1, alt=750, desc="რეგისტრაცია და ინფორმაცია.", en="Dedoplistskaro visitor center"),
      stop("არწივის ხეობა", "viewpoint", 41.3600, 46.3420, day=1, alt=600, en="Eagle canyon"),
      stop("მიჯნისყურე", "camp", 41.2700, 46.6630, day=1, alt=150, night=True, desc="ალაზნის ჭალა აზერბაიჯანის საზღვართან; კოტეჯები და ბანაკი.", en="Mijniskure"),
      stop("დედოფლისწყარო", "finish", 41.4618, 46.1077, day=2, alt=750, en="Dedoplistskaro"),
    ],
  },
  # ───────────── Tbilisi & around ─────────────
  {
    "slug": "turtle-lake-mtatsminda",
    "name": "კუს ტბა – მთაწმინდა",
    "name_en": "Turtle Lake – Mtatsminda",
    "region_id": "tbilisi",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 3,
    "distance_km": 8, "elevation_gain_m": 300, "elevation_loss_m": 200,
    "max_altitude_m": 800, "min_altitude_m": 680,
    "route_type": "one_way",
    "season_months": ALL_YEAR,
    "tags": ["forest", "views", "family", "public_transport", "city"],
    "summary": "თბილისის შიგნით ტყიანი ბილიკი კუს ტბიდან მთაწმინდის პარკამდე, ქალაქის ხედებით — იდეალური მოკლე ვარჯიში.",
    "description": "მონიშნული ბილიკი კუს ტბიდან ტყით მიდის მთაწმინდის ქედზე, ეთნოგრაფიული მუზეუმის გვერდით, და მთაწმინდის პარკთან ამოდის. შუა გზაზე რამდენიმე გასასვლელია ქალაქისკენ.",
    "difficulty_notes": "მარტივი ტყის ბილიკი, მცირე აღმართებით.",
    "getting_there": "კუს ტბამდე ტაქსით ან ბაგირით ვაკის პარკიდან. მთაწმინდიდან ჩამოსასვლელად — ფუნიკულიორი.",
    "water": "წყალი თან წაიღე; ბოლოს მთაწმინდის პარკში კაფეებია.",
    "permits": "არ არის საჭირო.",
    "dangers": "წვიმის შემდეგ ტალახიანია.",
    "mobile_coverage": "კარგი.",
    "gear": DAY_EASY,
    "tips": ["მზის ჩასვლაზე მთაწმინდიდან ქალაქის ხედი საუკეთესოა."],
    "sources": "https://wander-lush.org/day-hikes-near-tbilisi-georgia/",
    "stops": [
      stop("კუს ტბა", "start", 41.7006, 44.7539, alt=680, en="Turtle Lake"),
      stop("მთაწმინდის პარკი", "finish", 41.6948, 44.7864, alt=730, desc="ფუნიკულიორი, კაფეები, ქალაქის ხედი.", en="Mtatsminda park"),
    ],
  },
  {
    "slug": "kojori-tbilisi",
    "name": "კოჯორი (აზეულა) – თბილისი",
    "name_en": "Kojori (Azeula fortress) – Tbilisi",
    "region_id": "tbilisi",
    "difficulty": "moderate",
    "days_min": 1, "days_max": 1, "duration_hours": 4.5,
    "distance_km": 16, "elevation_gain_m": 250, "elevation_loss_m": 950,
    "max_altitude_m": 1400, "min_altitude_m": 600,
    "route_type": "one_way",
    "season_months": [3, 4, 5, 6, 7, 8, 9, 10, 11],
    "tags": ["history", "views", "forest", "public_transport"],
    "summary": "აზეულას ციხიდან ქედით და ტყით თბილისისკენ, ძირითადად დაღმართზე — კავკასიონის ხედით მოწმენდილ დღეს.",
    "description": "კოჯორში ავტობუსით ადიხარ, აზეულას ციხეს ათვალიერებ და ქედით თბილისისკენ ჩამოდიხარ — ტაბახმელის და ოკროყანის გავლით, მთაწმინდისკენ. მიმართულება ქვემოთკენ ბევრად სასიამოვნოა.",
    "difficulty_notes": "გრძელი, მაგრამ ძირითადად დაღმართი.",
    "getting_there": "კოჯორამდე ქალაქის ავტობუსით თავისუფლების მოედნიდან (~40 წთ) ან ტაქსით.",
    "water": "გზაზე სოფლებში მაღაზიებია, მაგრამ წყალი წაიღე.",
    "permits": "არ არის საჭირო.",
    "dangers": "გზის ზოგი მონაკვეთი მანქანების გზაზე გადის.",
    "mobile_coverage": "კარგი.",
    "gear": DAY_EASY + [POLES],
    "tips": ["ოფლაინ რუკაზე წინასწარ ჩაიწერე ტრეკი — ზოგან ბილიკები ერთმანეთს კვეთს."],
    "sources": "https://wander-lush.org/day-hikes-near-tbilisi-georgia/",
    "stops": [
      stop("აზეულას ციხე", "start", 41.6705, 44.6957, alt=1400, en="Azeula fortress"),
      stop("ტაბახმელა", "village", 41.6714, 44.7337, alt=1200, en="Tabakhmela"),
      stop("მთაწმინდა", "finish", 41.6948, 44.7864, alt=730, en="Mtatsminda"),
    ],
  },
  {
    "slug": "mtskheta-jvari",
    "name": "მცხეთა – ჯვრის მონასტერი",
    "name_en": "Mtskheta – Jvari monastery",
    "region_id": "tbilisi",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 2,
    "distance_km": 6, "elevation_gain_m": 220, "elevation_loss_m": 20,
    "max_altitude_m": 650, "min_altitude_m": 450,
    "route_type": "one_way",
    "season_months": ALL_YEAR,
    "tags": ["history", "views", "unesco", "public_transport"],
    "summary": "მცხეთიდან მტკვრისა და არაგვის შესართავის თავზე, VI საუკუნის ჯვრის მონასტრამდე — იუნესკოს მემკვიდრეობის ძეგლამდე ფეხით.",
    "description": "მცხეთიდან ხიდით მტკვარს გადადიხარ და ბორცვზე ამოდიხარ ჯვრის მონასტრამდე. ბილიკი მონიშნული არ არის, ნაწილი გზას მიუყვება. ზემოდან მცხეთა, სვეტიცხოველი და ორი მდინარის შესართავი ჩანს.",
    "difficulty_notes": "მოკლე აღმართი, ბილიკი ზოგან უცხოა — რუკა გამოგადგება.",
    "getting_there": "მცხეთამდე თბილისიდან მარშრუტკით დიდუბის სადგურიდან (~30 წთ).",
    "water": "წყალი თან წაიღე.",
    "permits": "არ არის საჭირო. ეკლესიაში შესაფერისი ჩაცმულობა.",
    "dangers": "ტრასის გადაკვეთისას ფრთხილად.",
    "mobile_coverage": "კარგი.",
    "gear": DAY_EASY,
    "tips": ["უკან მცხეთაში ტაქსით ჩამოდი და სვეტიცხოველი დაათვალიერე."],
    "sources": "https://wander-lush.org/day-hikes-near-tbilisi-georgia/",
    "stops": [
      stop("მცხეთა", "start", 41.8423, 44.7208, alt=460, en="Mtskheta"),
      stop("ჯვრის მონასტერი", "church", 41.8384, 44.7334, alt=650, en="Jvari monastery"),
    ],
  },
  {
    "slug": "martkopi-sabaduri",
    "name": "მარტყოფი – საბადურის ტყე",
    "name_en": "Martkopi monastery – Sabaduri forest",
    "region_id": "tbilisi",
    "difficulty": "moderate",
    "days_min": 1, "days_max": 1, "duration_hours": 4,
    "distance_km": 12, "elevation_gain_m": 500, "elevation_loss_m": 400,
    "max_altitude_m": 1350, "min_altitude_m": 900,
    "route_type": "one_way",
    "season_months": [4, 5, 6, 7, 8, 9, 10, 11],
    "tags": ["forest", "history", "national_park", "wildlife"],
    "summary": "თბილისის ეროვნულ პარკში, მარტყოფის VI საუკუნის მონასტრიდან საბადურის ხშირ ტყეში — წყაროებით და ჩრდილით ზაფხულის სიცხეშიც.",
    "description": "მარტყოფის მონასტრიდან ბილიკი ტყით ადის ქედზე და საბადურის ტყისკენ მიემართება. გზაზე რამდენიმე წყაროა. ბოლოს დათვების თავშესაფარია (ზოოლოგიური ცენტრი), სადაც გადარჩენილი დათვები ცხოვრობენ.",
    "difficulty_notes": "ზომიერი აღმართი ტყეში; წვიმის შემდეგ ტალახიანი.",
    "getting_there": "ნორიომდე ან მარტყოფამდე მარშრუტკით (~40 წთ), შემდეგ ტაქსით მონასტრამდე. ფინიშიდან ტაქსი წინასწარ შეუთანხმე.",
    "water": "ტყეში წყაროებია.",
    "permits": "არ არის საჭირო.",
    "dangers": "ტალახი წვიმის შემდეგ. ტყეში ბილიკები ერთმანეთს კვეთს.",
    "mobile_coverage": "ნაწილობრივ.",
    "gear": DAY_EASY + [BOOTS],
    "tips": ["შემოდგომით საბადურის წიფლნარი განსაკუთრებით ლამაზია."],
    "sources": "https://wander-lush.org/day-hikes-near-tbilisi-georgia/",
    "stops": [
      stop("მარტყოფის მონასტერი", "start", 41.8004, 45.0001, alt=900, en="Martkopi monastery"),
      stop("საბადურის ტყე", "finish", 41.8642, 44.9810, alt=1300, en="Sabaduri forest"),
    ],
  },
  {
    "slug": "birtvisi-canyon",
    "name": "ბირთვისის კანიონი და ციხე",
    "name_en": "Birtvisi canyon and fortress",
    "region_id": "tbilisi",
    "difficulty": "moderate",
    "days_min": 1, "days_max": 1, "duration_hours": 4,
    "distance_km": 9, "elevation_gain_m": 400, "elevation_loss_m": 400,
    "max_altitude_m": 1050, "min_altitude_m": 750,
    "route_type": "out_and_back",
    "season_months": [3, 4, 5, 6, 9, 10, 11],
    "tags": ["canyon", "history", "views", "scrambling"],
    "summary": "\"ქართული დოლომიტები\" თბილისიდან ერთ საათში: კლდოვანი კანიონი და შუასაუკუნეების ციხე კლდეებს შორის.",
    "description": "სოფელ თბისიდან ბილიკი ალგეთის კანიონს მიუყვება, შემდეგ კლდეებს შორის ციცაბოდ ადის ბირთვისის ციხის ნანგრევებამდე. ზოგან ხელების გამოყენება მოგიწევს. ზემოდან კლდოვანი სვეტების ტყე იშლება.",
    "difficulty_notes": "მოკლეა, მაგრამ ციცაბო, ზოგან მარტივი ცოცვით. ბავშვებისთვის და სიმაღლის შიშის მქონეთათვის — ფრთხილად.",
    "getting_there": "თბისამდე მარშრუტკით (~1–1.25 სთ) ან ტაქსით. ბოლო მარშრუტკა ~16:00-ზე ბრუნდება.",
    "water": "წყარო არ არის — 1.5 ლ წაიღე.",
    "permits": "არ არის საჭირო.",
    "dangers": "ციცაბო და ქვიანი ადგილები, ზაფხულში სიცხე და გველები. წვიმაში კლდე მოლიპულია.",
    "mobile_coverage": "ნაწილობრივ.",
    "gear": DAY_EASY + [BOOTS],
    "tips": ["Wikiloc-ის ან Organic Maps-ის ტრეკი ჩამოტვირთე — ბილიკი ზოგან გაურკვეველია."],
    "sources": "https://wander-lush.org/day-hikes-near-tbilisi-georgia/",
    "stops": [
      stop("თბისი", "start", 41.5880, 44.5052, alt=750, en="Tbisi"),
      stop("ბირთვისის ციხე", "fortress", 41.6040, 44.4869, alt=1050, en="Birtvisi fortress"),
    ],
  },
  {
    "slug": "dashbashi-canyon",
    "name": "დაშბაშის (წალკის) კანიონი",
    "name_en": "Dashbashi (Tsalka) canyon",
    "region_id": "tbilisi",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 2,
    "distance_km": 3.6, "elevation_gain_m": 250, "elevation_loss_m": 250,
    "max_altitude_m": 1450, "min_altitude_m": 1110,
    "route_type": "out_and_back",
    "season_months": [4, 5, 6, 7, 8, 9, 10],
    "tags": ["canyon", "waterfall", "family"],
    "summary": "ბაზალტის კანიონი ზურმუხტისფერი ხავსიანი ჩანჩქერით და მინის 'ბრილიანტის ხიდით' — მარტივი ბილიკი კიბეებით.",
    "description": "კანიონში აღჭურვილი ბილიკი, მოაჯირებით და კიბეებით ჩადის მდინარემდე და ხავსიან ჩანჩქერამდე. კანიონზე გადებულია ~240 მეტრიანი მინის ხიდი (ცალკე ფასიანი).",
    "difficulty_notes": "მარტივი, მაგრამ უკან ამოსვლა კიბეებზე ცოტა დამღლელია.",
    "getting_there": "~110 კმ თბილისიდან. მარშრუტკა ნავთლუღის სადგურიდან (დილით) ან მანქანით.",
    "water": "წყალი თან წაიღე.",
    "permits": "კანიონი უფასოა; მინის ხიდი ფასიანია და ცუდ ამინდში იხურება.",
    "dangers": "კიბეები წვიმაში მოლიპულია.",
    "mobile_coverage": "კარგი.",
    "gear": DAY_EASY,
    "tips": ["შაბათ-კვირას ხიდთან რიგი გრძელია — სამუშაო დღეს წადი."],
    "sources": "https://www.redfedoradiary.com/dashbashi-canyon/",
    "stops": [
      stop("დაშბაშის კანიონის შესასვლელი", "start", 41.5694, 44.1452, alt=1450, en="Dashbashi canyon entrance"),
      stop("ხავსიანი ჩანჩქერი", "waterfall", 41.5677, 44.1386, alt=1150, en="Dashbashi waterfall"),
    ],
  },
  # ───────────── Borjomi / Samtskhe-Javakheti ─────────────
  {
    "slug": "romanov-trail-borjomi",
    "name": "ნიკოლოზ რომანოვის ბილიკი (ბორჯომ-ხარაგაული #1)",
    "name_en": "Borjomi-Kharagauli trail #1 (Nikoloz Romanov)",
    "region_id": "borjomi",
    "difficulty": "moderate",
    "days_min": 3, "days_max": 3,
    "distance_km": 43, "elevation_gain_m": 1800, "elevation_loss_m": 2200,
    "max_altitude_m": 2198, "min_altitude_m": 540,
    "route_type": "one_way",
    "season_months": [5, 6, 7, 8, 9, 10],
    "tags": ["forest", "huts", "national_park", "views", "flowers"],
    "summary": "ბორჯომ-ხარაგაულის ეროვნული პარკის კლასიკა: ლიკანიდან ლომისმთის გავლით მარელისამდე, ტყეებით, მდელოებით და თავშესაფრებით.",
    "description": (
      "პირველ დღეს ლიკანიდან (~930 მ) ტყით ადიხარ ლომისმთის თავშესაფრამდე (15 კმ). მეორე დღეს ქედზე, ლომისმთის წმ. გიორგის ეკლესიის და "
      "ხედების გავლით, სახვლარის თავშესაფრამდე მიდიხარ (18 კმ). მესამე დღეს კოლხურ ტყეში ჩადიხარ მარელისამდე (10 კმ). მაის–ივნისში დეკა ყვავის."
    ),
    "difficulty_notes": "სამი ზომიერი დღე. პირველ დღეს ~1 200 მ აღმართია.",
    "getting_there": "ბორჯომამდე თბილისიდან მატარებლით ან მარშრუტკით (~2.5 სთ). ლიკანის სადარაჯო ბორჯომის ცენტრიდან ახლოსაა. მარელისიდან ხარაგაულში/თბილისში მატარებლით.",
    "accommodation": "სახვლარის თავშესაფარი და კარვის ადგილები. რუკის მონაცემებით ლომისმთის თავშესაფარი დამწვარია — გასვლამდე ვიზიტორთა ცენტრში გადაამოწმე და კარავი წაიღე.",
    "water": "თავშესაფრებთან წყაროებია.",
    "permits": "გასვლამდე ბორჯომის ვიზიტორთა ცენტრში რეგისტრაცია სავალდებულოა.",
    "dangers": "ტყეში დათვი შეიძლება შეგხვდეს (იშვიათად) — საჭმელი დახურულად შეინახე. ნისლში ქედზე ორიენტირება.",
    "mobile_coverage": "ქედზე ნაწილობრივ.",
    "gear": MULTI_GUESTHOUSE + [SLEEPING_BAG, FOOD_DAYS],
    "tips": ["ბილიკი ცხენითაც გაივლება — ცხენების დაჯავშნა ვიზიტორთა ცენტრშია შესაძლებელი."],
    "sources": "https://www.apa.gov.ge/en/eco-tourism/Trails/bordjom-xaragaulis-turistuli-bilikebi-satesto/nikoloz-romanovis-biliki",
    "stops": [
      stop("ლიკანის სადარაჯო", "start", 41.8261, 43.3540, day=1, alt=930, en="Likani ranger station"),
      stop("ლომისმთის თავშესაფარი", "camp", 41.8600, 43.2500, day=1, alt=2000, night=True, desc="თავშესაფარი შეიძლება არ მუშაობდეს — კარვის ადგილი.", en="Lomismta shelter"),
      stop("ლომისმთა (2 198 მ)", "peak", 41.8674, 43.2435, day=2, alt=2198, desc="პარკის ერთ-ერთი საუკეთესო ხედი; ახლოს წმ. გიორგის ეკლესიაა.", en="Lomismta church"),
      stop("სახვლარის თავშესაფარი", "hut", 41.8949, 43.2046, day=2, alt=1025, night=True, en="Sakhvlari shelter"),
      stop("მარელისი", "finish", 41.9640, 43.2110, day=3, alt=540, en="Marelisi"),
    ],
  },
  {
    "slug": "st-andrew-trail-borjomi",
    "name": "წმ. ანდრია პირველწოდებულის ბილიკი (ბორჯომ-ხარაგაული #2)",
    "name_en": "St. Andrew trail (Borjomi-Kharagauli #2)",
    "region_id": "borjomi",
    "difficulty": "hard",
    "days_min": 4, "days_max": 4,
    "distance_km": 54, "elevation_gain_m": 2700, "elevation_loss_m": 3100,
    "max_altitude_m": 2642, "min_altitude_m": 540,
    "route_type": "one_way",
    "season_months": [6, 7, 8, 9],
    "tags": ["forest", "huts", "national_park", "peak", "wildlife", "views"],
    "summary": "ოთხდღიანი ტრავერსი აწყურიდან მარელისამდე, პარკის უმაღლეს მწვერვალ სამეცხვარიოზე (2 642 მ) — ჯიხვის ჰაბიტატი და ფართო პანორამები.",
    "description": (
      "აწყურის სადარაჯოდან ბილიკი შერეული ტყით ადის ამარათის თავშესაფრამდე, შემდეგ ალპური მდელოებით სამეცხვარიოს მწვერვალზე (2 642 მ) — "
      "პარკის უმაღლეს წერტილზე, რკინის ჯვრით. დაღმართი სახვლარისა და მარელისის კოლხური ტყეებისკენ მიდის."
    ),
    "difficulty_notes": "ოთხი დღე, დიდი აღმართ-დაღმართები და მოშორებული მონაკვეთები.",
    "getting_there": "აწყურამდე ბორჯომიდან ან ახალციხიდან. მარელისიდან მატარებლით.",
    "accommodation": "ამარათის, სამეცხვარიოს და სახვლარის თავშესაფრები ან კარავი.",
    "water": "თავშესაფრებთან წყაროებია; ქედზე — ცოტა.",
    "permits": "ბორჯომის ვიზიტორთა ცენტრში რეგისტრაცია სავალდებულოა.",
    "dangers": "ცვალებადი ამინდი ქედზე; დათვები (იშვიათად).",
    "mobile_coverage": "ქედზე ნაწილობრივ.",
    "gear": MULTI_CAMP,
    "tips": ["თავშესაფრებში ადგილის ხელმისაწვდომობა ვიზიტორთა ცენტრში გადაამოწმე."],
    "sources": "https://apa.gov.ge/en/eco-tourism/Trails/bordjom-xaragaulis-turistuli-bilikebi-satesto/2-wminda-andria-pirvelwodebulis-biliki",
    "stops": [
      stop("აწყურის სადარაჯო", "start", 41.7330, 43.1600, day=1, alt=1000, en="Atskuri ranger station"),
      stop("ამარათის თავშესაფარი", "hut", 41.7860, 43.1250, day=1, alt=1900, night=True, en="Amarati shelter"),
      stop("სამეცხვარიოს მწვერვალი", "peak", 41.8155, 43.1490, day=2, alt=2642, en="Mt. Sametskhvario"),
      stop("სახვლარის თავშესაფარი", "hut", 41.9300, 43.1990, day=3, alt=1025, night=True, en="Sakhvlari shelter"),
      stop("მარელისი", "finish", 41.9640, 43.2110, day=4, alt=540, en="Marelisi"),
    ],
  },
  {
    "slug": "footprint-trail-borjomi",
    "name": "ნაკვალევის ბილიკი: ლიკანი – ყვაბისხევი",
    "name_en": "Footprint trail: Likani – Kvabiskhevi",
    "region_id": "borjomi",
    "difficulty": "moderate",
    "days_min": 1, "days_max": 1, "duration_hours": 6,
    "distance_km": 13, "elevation_gain_m": 800, "elevation_loss_m": 800,
    "max_altitude_m": 1650, "min_altitude_m": 850,
    "route_type": "one_way",
    "season_months": [4, 5, 6, 7, 8, 9, 10, 11],
    "tags": ["forest", "views", "national_park", "history"],
    "summary": "ბორჯომის საუკეთესო დღიური ლაშქრობა: ლიკანის ხეობის ურთხლით, ქედზე პანორამით და ყვაბისხევის კანიონში ჩასვლით.",
    "description": "ლიკანის ხეობიდან რომანოვის ბილიკით ადიხარ (~3 სთ), შემდეგ #6 ნაკვალევის ბილიკზე გადადიხარ, რომელიც ქედზე პანორამებით მიდის და ციცაბოდ ჩადის ყვაბისხევის ხეობაში, მარიამწმინდის ეკლესიის გავლით.",
    "difficulty_notes": "~800 მ აღმართი და ციცაბო დაღმართი ყვაბისხევისკენ.",
    "getting_there": "ლიკანი ბორჯომის ცენტრთან ახლოსაა. ყვაბისხევიდან ბორჯომში ტაქსით (~15 წთ).",
    "water": "წყალი თან წაიღე.",
    "permits": "ვიზიტორთა ცენტრში რეგისტრაცია.",
    "dangers": "დაღმართი ყვაბისხევისკენ ციცაბო და მოლიპულია წვიმაში.",
    "mobile_coverage": "ნაწილობრივ.",
    "gear": DAY_MOUNTAIN,
    "tips": ["ფინიშთან ახლოს სოფელშია ადგილობრივი პროდუქტები — ყველი, თაფლი."],
    "sources": "https://apa.gov.ge/en/eco-tourism/Trails/bordjom-xaragaulis-turistuli-bilikebi-satesto/6-nakvalevis-biliki ; https://www.caucasus-trekking.com/best-hikes",
    "stops": [
      stop("ლიკანის სადარაჯო", "start", 41.8261, 43.3540, alt=930, en="Likani"),
      stop("პარკის რუკის წერტილი (ქედი)", "viewpoint", 41.8456, 43.3185, alt=1600, en="Ridge viewpoint"),
      stop("მარიამწმინდის ეკლესია", "church", 41.8466, 43.2797, alt=1100, en="Mariamtsminda church"),
      stop("ყვაბისხევი", "finish", 41.8379, 43.2683, alt=850, en="Kvabiskhevi"),
    ],
  },
  {
    "slug": "bakuriani-tabatskuri-ridge",
    "name": "ბაკურიანი – ტაბაწყურის ნაკრძალის ქედი",
    "name_en": "Bakuriani – Ktsia-Tabatskuri reserve ridge",
    "region_id": "borjomi",
    "difficulty": "moderate",
    "days_min": 1, "days_max": 2, "duration_hours": 7,
    "distance_km": 19.5, "elevation_gain_m": 1170, "elevation_loss_m": 840,
    "max_altitude_m": 2450, "min_altitude_m": 1650,
    "route_type": "loop",
    "season_months": [5, 6, 7, 8, 9, 10],
    "tags": ["views", "forest", "lakes", "camping"],
    "summary": "ბაკურიანის ფიჭვნარიდან ქედზე, ტაბაწყურის ტბისა და ჯავახეთის ზეგნის ხედებით — ერთ ან ორ დღეში.",
    "description": "დიდი მიტარბიდან ბილიკი ფიჭვნარით ადის ჩრდილოეთის ქედზე (~2 450 მ), საიდანაც ტაბაწყურის ტბა და ქციის ხეობა ჩანს, შემდეგ ბაკურიანში ბრუნდება. ორ დღედ გაყოფისას შუაში კარვის ადგილია.",
    "difficulty_notes": "ზომიერი, ძირითადად მარტივი ორიენტირებით.",
    "getting_there": "ბაკურიანამდე თბილისიდან მარშრუტკით (დღეში რამდენჯერმე) ან ბორჯომიდან 'კუკუშკა' მატარებლით. დიდ მიტარბამდე ~6 კმ (ტაქსი).",
    "accommodation": "ბაკურიანში ბევრი სასტუმრო.",
    "water": "ბილიკზე წყაროებია.",
    "permits": "არ არის საჭირო.",
    "dangers": "ზამთარში სათხილამურო ფერდობებზე და თოვლმავლებთან ფრთხილად.",
    "mobile_coverage": "უმეტესად არის.",
    "gear": DAY_MOUNTAIN,
    "tips": ["იანვარ–მარტი არ შეარჩიო — თოვლი და სათხილამურო ტრაფიკია."],
    "sources": "https://www.caucasus-trekking.com/treks/explore-tabatskuri-reserve-from-bakuriani",
    "stops": [
      stop("დიდი მიტარბი", "start", 41.7697, 43.4646, alt=1650, en="Didi Mitarbi"),
      stop("ქედი ტაბაწყურის ხედით", "viewpoint", 41.7360, 43.5480, alt=2450, en="Ridge viewpoint"),
      stop("ბაკურიანი", "finish", 41.7499, 43.5303, alt=1700, en="Bakuriani"),
    ],
  },
]
