from common import *

ROUTES = [
  # ───────────── Imereti ─────────────
  {
    "slug": "okatse-canyon",
    "name": "ოკაცეს კანიონი",
    "name_en": "Okatse canyon",
    "region_id": "imereti",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 2.5,
    "distance_km": 6, "elevation_gain_m": 200, "elevation_loss_m": 200,
    "max_altitude_m": 650, "min_altitude_m": 500,
    "route_type": "out_and_back",
    "season_months": ALL_YEAR,
    "tags": ["canyon", "forest", "family", "views"],
    "summary": "დადიანების ტყით კანიონის კლდეზე დამაგრებულ ბილიკამდე, რომელიც 140 მეტრის სიმაღლეზე ეკიდება — ოჯახური და შთამბეჭდავი.",
    "description": "ვიზიტორთა ცენტრიდან (სოფელი გორდი) ბილიკი დადიანების ძველ ტყეში გადის, შემდეგ კი იწყება ~780 მეტრიანი ბილიკი, რომელიც კანიონის კედელზეა დამაგრებული და ბოლოს კანიონის თავზე გადაკიდებული მოედნით მთავრდება.",
    "difficulty_notes": "ფიზიკურად მარტივი; სიმაღლის შიშის მქონეთათვის ჩამოკიდებული ბილიკი შეიძლება რთული იყოს.",
    "getting_there": "ქუთაისიდან ~1 სთ (ხონის გავლით). ტაქსით ან ტურით; ხშირად მარტვილის კანიონთან და კინჩხას ჩანჩქერთან ერთად აერთიანებენ.",
    "water": "ვიზიტორთა ცენტრთან კაფეა.",
    "permits": "შესვლა ფასიანია (ბილეთი ვიზიტორთა ცენტრში). ორშაბათობით ზოგჯერ დაკეტილია — წინასწარ გადაამოწმე.",
    "dangers": "კიბეები წვიმაში მოლიპულია.",
    "mobile_coverage": "კარგი.",
    "gear": DAY_EASY,
    "tips": ["დილის პირველ საათებში წადი — შუადღისას ტურისტული ჯგუფები მოდის."],
    "sources": "https://georgia.to/okatse-canyon-hiking-trails/",
    "stops": [
      stop("ოკაცეს ვიზიტორთა ცენტრი (გორდი)", "start", 42.4586, 42.5519, alt=600, en="Okatse visitor center"),
      stop("ოკაცეს კანიონის დაკიდებული ბილიკი", "viewpoint", 42.4552, 42.5381, alt=520, en="Okatse hanging walkway"),
    ],
  },
  {
    "slug": "kinchkha-waterfall",
    "name": "კინჩხას ჩანჩქერი",
    "name_en": "Kinchkha waterfall",
    "region_id": "imereti",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 1.5,
    "distance_km": 2, "elevation_gain_m": 100, "elevation_loss_m": 100,
    "max_altitude_m": 900, "min_altitude_m": 780,
    "route_type": "out_and_back",
    "season_months": [3, 4, 5, 6, 7, 8, 9, 10, 11],
    "tags": ["waterfall", "forest", "family"],
    "summary": "ტყიანი ბილიკი 70-მეტრიან კინჩხას ჩანჩქერამდე, ოკაცეს კანიონის მეზობლად — განსაკუთრებით ლამაზი გაზაფხულზე.",
    "description": "სოფელ კინჩხადან მოკლე ბილიკი ტყით ჩანჩქერის ძირამდე და ზედა სანახავ მოედნამდე მიდის. გაზაფხულზე, როცა წყალი ბევრია, ჩანჩქერი ყველაზე შთამბეჭდავია.",
    "difficulty_notes": "მოკლე და მარტივი.",
    "getting_there": "ოკაცეს კანიონიდან ~10 წთ მანქანით.",
    "water": "წყალი თან წაიღე.",
    "permits": "შესვლა შეიძლება ფასიანი იყოს.",
    "dangers": "სველი ქვები ჩანჩქერთან.",
    "mobile_coverage": "კარგი.",
    "gear": DAY_EASY,
    "tips": ["ოკაცესთან ერთად ერთ ნახევარ დღეში ეტევა."],
    "sources": "https://georgia.to/okatse-canyon-hiking-trails/",
    "stops": [
      stop("კინჩხა", "start", 42.4950, 42.5530, alt=780, en="Kinchkha"),
      stop("კინჩხას ჩანჩქერი", "waterfall", 42.4979, 42.5584, alt=900, en="Kinchkha waterfall"),
    ],
  },
  # ───────────── Racha-Lechkhumi ─────────────
  {
    "slug": "mount-khvamli",
    "name": "ხვამლის მთა",
    "name_en": "Mount Khvamli",
    "region_id": "racha",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 2.5,
    "distance_km": 4, "elevation_gain_m": 490, "elevation_loss_m": 490,
    "max_altitude_m": 2001, "min_altitude_m": 1510,
    "route_type": "out_and_back",
    "season_months": [5, 6, 7, 8, 9, 10],
    "tags": ["peak", "views", "history", "legend"],
    "summary": "ამირანისა და პრომეთეს ლეგენდების მთა: მოკლე ასვლა კირქვის პლატოზე, საიდანაც იმერეთი, რაჭა და ლეჩხუმი ჩანს.",
    "description": "ოკურეშის მხრიდან, მანქანის სადგომიდან ბილიკი ბოლო 2 კილომეტრზე ადის ხვამლის კირქვულ თავზე (~2 000 მ). ლეგენდით აქ მიაჯაჭვეს ამირანი. ზემოდან ხედი საოცარია, განსაკუთრებით მზის ამოსვლისას.",
    "difficulty_notes": "მოკლე, მაგრამ ციცაბო; კრატერის კიდეზე ვიწრო ადგილები.",
    "getting_there": "ქუთაისიდან ~1.5 სთ მანქანით (ცაგერის მხრიდან, ოკურეშის გზით). საზოგადოებრივი ტრანსპორტით რთულია.",
    "water": "სადგომთან წყაროა.",
    "permits": "არ არის საჭირო.",
    "dangers": "მოლიპული კლდე წვიმაში; ზამთარში თოვლი.",
    "mobile_coverage": "ნაწილობრივ.",
    "gear": DAY_EASY + [BOOTS],
    "tips": ["მზის ამოსვლის სანახავად ფანარით ადი — ხედი ღრუბლების ზღვაზე ხშირად ჩნდება."],
    "sources": "https://www.caucasus-trekking.com/treks/mount-khvamli-hike",
    "stops": [
      stop("ხვამლის სადგომი (ოკურეშის გზა)", "start", 42.4413, 42.6634, alt=1510, en="Khvamli parking"),
      stop("ხვამლის თავი", "peak", 42.4392, 42.6517, alt=2001, en="Mt. Khvamli"),
    ],
  },
  # ───────────── Samegrelo ─────────────
  {
    "slug": "martvili-canyon",
    "name": "მარტვილის კანიონი",
    "name_en": "Martvili canyon",
    "region_id": "samegrelo",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 1.5,
    "distance_km": 2, "elevation_gain_m": 60, "elevation_loss_m": 60,
    "max_altitude_m": 250, "min_altitude_m": 200,
    "route_type": "loop",
    "season_months": ALL_YEAR,
    "tags": ["canyon", "waterfall", "family"],
    "summary": "მოკლე ბილიკი ზურმუხტისფერ ხეობაში ჩანჩქერებით და ნავით გასეირნება აბაშის კანიონში — ყველაზე მარტივი ბუნებრივი სასეირნო.",
    "description": "ვიზიტორთა ცენტრიდან ბილიკი კანიონის კიდეზე და ქვემოთ, ჩანჩქერებთან მიდის. ცალკე ფასად შეგიძლია ნავით კანიონში შეხვიდე. წვიმიან ამინდში ნავით მომსახურება შეიძლება შეჩერდეს.",
    "difficulty_notes": "ძალიან მარტივი.",
    "getting_there": "ქუთაისიდან ~1 სთ, მარტვილიდან ~15 წთ.",
    "water": "ვიზიტორთა ცენტრთან კაფეა.",
    "permits": "შესვლა და ნავი ფასიანია.",
    "dangers": "სველი კიბეები.",
    "mobile_coverage": "კარგი.",
    "gear": DAY_EASY,
    "tips": ["ზაფხულში დილით ადრე წადი — რიგი გრძელდება."],
    "sources": "https://georgia.travel",
    "stops": [
      stop("მარტვილის კანიონის ვიზიტორთა ცენტრი", "start", 42.4574, 42.3772, alt=250, en="Martvili canyon"),
      stop("ჩანჩქერები", "waterfall", 42.4588, 42.3758, alt=210, en="Waterfalls"),
    ],
  },
  {
    "slug": "tobavarchkhili-lakes",
    "name": "ტობავარჩხილის (ვერცხლის) ტბები",
    "name_en": "Tobavarchkhili (Silver) lakes",
    "region_id": "samegrelo",
    "difficulty": "hard",
    "days_min": 4, "days_max": 5,
    "distance_km": 70, "elevation_gain_m": 5000, "elevation_loss_m": 4900,
    "max_altitude_m": 2905, "min_altitude_m": 260,
    "route_type": "one_way",
    "season_months": [7, 8, 9],
    "tags": ["lakes", "pass", "camping", "remote", "forest"],
    "summary": "ეგრისის ქედის მაღალმთიანი ტბების მოშორებული ტრეკი — მხოლოდ კარვით, ოთხი უღელტეხილით და დიდი აღმართ-დაღმართით.",
    "description": (
      "მუხურიდან (ან ნატიფურის ქოხამდე ჯიპით) ბილიკი კოლხური ტყით ადის ეგრისის ქედზე. ტობავარჩხილის ტბა ~2 650 მ სიმაღლეზეა და ირგვლივ ათეულობით პატარა ტბაა. "
      "სოფლები და სასტუმროები მარშრუტზე არ არის. 2026 წლის მონაცემით მაგანას ხეობაში ბილიკი ჩამოიშალა, ამიტომ კლასიკური ჩასვლა სკურისკენ გაუვალია — "
      "გამოიყენე ოკარეს უღელტეხილის ალტერნატივა ან ხაიშისკენ ჩასვლა."
    ),
    "difficulty_notes": "ძალიან დიდი აღმართ-დაღმართი, უღელტეხილები, მდინარეების გადალახვა და გადაკარგული ტერიტორია, სადაც დახმარება შორსაა.",
    "getting_there": "მუხურამდე ზუგდიდიდან მარშრუტკით (დილით) ან ტაქსით. ნატიფურის ქოხამდე ჯიპით შეიძლება. ფინიშიდან (ხაიში/სკური) — ტაქსი ან მარშრუტკა ზუგდიდისკენ.",
    "accommodation": "მხოლოდ კარავი (ნატიფურზე ქოხია).",
    "water": "წყაროები ბევრია.",
    "permits": "არ არის საჭირო.",
    "dangers": "ივლისამდე უღელტეხილებზე თოვლი სიცოცხლისთვის სახიფათოა. ნისლი, მოლიპული ტყე, მდინარეები. ბილიკის ჩამოშლილი მონაკვეთები — გასვლამდე გადაამოწმე მდგომარეობა.",
    "mobile_coverage": "თითქმის არ არის.",
    "gear": MULTI_CAMP + [SANDALS],
    "tips": ["ხუთი დღე დაგეგმე, მაშინაც კი თუ ოთხში გეგმავ — ნისლი ხშირად აჩერებს მოძრაობას."],
    "sources": "https://www.caucasus-trekking.com/treks/trek-to-tobavarchkhili-lakes ; https://www.caucasus-trekking.com/treks/toba",
    "stops": [
      stop("მუხური", "start", 42.6409, 42.1654, day=1, alt=260, en="Mukhuri"),
      stop("ნატიფურის ქოხი", "hut", 42.7083, 42.1650, day=1, alt=1700, night=True, en="Natipuru hut"),
      stop("ტობავარჩხილის ტბა", "lake", 42.7390, 42.1830, day=2, alt=2650, night=True, desc="ეგრისის ქედის მთავარი ტბა, ირგვლივ პატარა ტბებით.", en="Tobavarchkhili lake"),
      stop("ჯოლორას ბანაკი", "camp", 42.7710, 42.2180, day=3, alt=2200, night=True, en="Jolora camp"),
      stop("ხაიში", "finish", 42.9567, 42.2006, day=5, alt=700, en="Khaishi"),
    ],
  },
  # ───────────── Adjara ─────────────
  {
    "slug": "mtirala-tsablnari",
    "name": "მტირალას ეროვნული პარკი — წაბლნარის ბილიკი",
    "name_en": "Mtirala NP — Tsablnari trail",
    "region_id": "adjara",
    "difficulty": "easy",
    "days_min": 1, "days_max": 1, "duration_hours": 3,
    "distance_km": 7, "elevation_gain_m": 200, "elevation_loss_m": 200,
    "max_altitude_m": 442, "min_altitude_m": 265,
    "route_type": "loop",
    "season_months": ALL_YEAR,
    "tags": ["forest", "waterfall", "lakes", "family", "national_park"],
    "summary": "ბათუმიდან ახლოს, საქართველოს ყველაზე წვიმიან ტყეში: კოლხური წაბლნარი, 28-მეტრიანი ჩანჩქერი და პატარა ტბა.",
    "description": "ჩაქვისთავის ვიზიტორთა ცენტრიდან ბილიკი კოლხურ ტყეში გადის, ჩანჩქერთან და ტბასთან. ჩანჩქერთან კარვის ადგილი და მწვადის ადგილებია, პარკში ზიპლაინიც მუშაობს.",
    "difficulty_notes": "მარტივი, მაგრამ ხშირად ტალახიანი — მტირალა საქართველოს ყველაზე წვიმიანი ადგილია.",
    "getting_there": "ბათუმიდან ჩაქვამდე და ჩაქვისთავამდე (~40 წთ ტაქსით).",
    "water": "ნაკადულები ბევრია.",
    "permits": "ვიზიტორთა ცენტრში რეგისტრაცია; შესვლა შეიძლება ფასიანი იყოს.",
    "dangers": "ტალახი და მოლიპული ქვები.",
    "mobile_coverage": "ნაწილობრივ.",
    "gear": DAY_EASY + [BOOTS, RAIN],
    "tips": ["თუ მეტი გინდა, ორდღიანი 'წივწყაროს' ბილიკიც არსებობს."],
    "sources": "https://nationalparks.ge/en/site/mtiralanp/tripsInner/44",
    "stops": [
      stop("ჩაქვისთავის ვიზიტორთა ცენტრი", "start", 41.6703, 41.8622, alt=265, en="Chakvistavi visitor center"),
      stop("მტირალას ჩანჩქერი", "waterfall", 41.6640, 41.8780, alt=400, en="Mtirala waterfall"),
    ],
  },
  {
    "slug": "machakhela-kokoleti",
    "name": "მაჭახელას ეროვნული პარკი — ქოქოლეთის ბილიკი",
    "name_en": "Machakhela NP — Kokoleti trail",
    "region_id": "adjara",
    "difficulty": "moderate",
    "days_min": 1, "days_max": 1, "duration_hours": 6,
    "distance_km": 15, "elevation_gain_m": 700, "elevation_loss_m": 700,
    "max_altitude_m": 1100, "min_altitude_m": 300,
    "route_type": "loop",
    "season_months": [4, 5, 6, 7, 8, 9, 10, 11],
    "tags": ["forest", "villages", "national_park", "border_zone", "views"],
    "summary": "ზემო მაჭახელის ექვსი ისტორიული სოფელი, კოლხური ტყე და ხედი თურქეთის კამილის ნაკრძალზე — სასაზღვრო საშვით.",
    "description": "ვიზიტორთა ცენტრიდან ბილიკი ტყით ადის სანახავ წერტილამდე, საიდანაც თურქეთის მხარე ჩანს, და ქვემო ქოქოლეთის გავლით ბრუნდება. გზაზე პიკნიკის და კარვის ადგილი ცივი წყაროთი.",
    "difficulty_notes": "ზომიერი, ტყის ბილიკი.",
    "getting_there": "ბათუმიდან ~1 სთ მაჭახელას ხეობით.",
    "water": "ცივი წყარო პიკნიკის ადგილზე.",
    "permits": "სასაზღვრო ზონაა: საჭიროა სასაზღვრო პოლიციის დროებითი ყოფნის საშვი (განაცხადი სასაზღვრო პოლიციის ვებგვერდის ინსტრუქციით, წინასწარ). დაუკავშირდი პარკის ადმინისტრაციას.",
    "dangers": "საზღვართან ნუ მიხვალ მონიშნული ბილიკის გარეთ.",
    "mobile_coverage": "ნაწილობრივ (შეიძლება თურქული ქსელი აიღოს).",
    "gear": DAY_MOUNTAIN + [ID],
    "tips": ["საშვს რამდენიმე დღე სჭირდება — წინასწარ მოამზადე."],
    "sources": "https://apa.gov.ge/en/eco-tourism/Trails/machaxelas-erovnuli-parki/qoqoletis-biliki",
    "stops": [
      stop("მაჭახელას ვიზიტორთა ცენტრი", "start", 41.4950, 41.8600, alt=300, en="Machakhela visitor center"),
      stop("ქოქოლეთის სანახავი", "viewpoint", 41.4800, 41.8950, alt=1100, en="Kokoleti viewpoint"),
      stop("ქვემო ქოქოლეთი", "village", 41.4860, 41.8780, alt=700, en="Kvemo Kokoleti"),
    ],
  },
  {
    "slug": "kintrishi-tbikeli-lake",
    "name": "კინტრიშის ეროვნული პარკი — ურთხელი და ტბიყელის ტბა",
    "name_en": "Kintrishi NP — Yew forest and Lake Tbikeli",
    "region_id": "adjara",
    "difficulty": "moderate",
    "days_min": 2, "days_max": 2,
    "distance_km": 37, "elevation_gain_m": 1700, "elevation_loss_m": 1700,
    "max_altitude_m": 2000, "min_altitude_m": 400,
    "route_type": "out_and_back",
    "season_months": [5, 6, 7, 8, 9, 10],
    "tags": ["lakes", "forest", "history", "national_park", "camping"],
    "summary": "მესამეული პერიოდის ურთხლის ტყით, VIII–IX საუკუნის ეკლესიის ნანგრევებით და მაღალმთიანი ოვალური ტბით — ორდღიანი ლაშქრობა აჭარის მთებში.",
    "description": "ცხემვანის ვიზიტორთა თავშესაფრიდან ბილიკი კინტრიშის ხეობის რელიქტურ ურთხლის, წაბლისა და წიფლის ტყეებში გადის, ხინოწმინდის ეკლესიის ნანგრევების გავლით, და ~1 900–2 000 მ სიმაღლეზე მდებარე ტბიყელის ტბამდე მიდის. ტბაში წითელ წიგნში შეტანილი კავკასიური ტრიტონი ბინადრობს.",
    "difficulty_notes": "ორი გრძელი დღე და დიდი აღმართი ტყეში.",
    "getting_there": "ქობულეთიდან კინტრიშის ხეობით ცხემვანამდე (ტაქსით).",
    "accommodation": "ცხემვანის ვიზიტორთა თავშესაფარი; ტბასთან კარავი.",
    "water": "ნაკადულები ბევრია.",
    "permits": "დეტალები და რეგისტრაცია პარკის ადმინისტრაციასთან.",
    "dangers": "ნისლი და წვიმა ხშირია; ტბა ზამთარში იყინება.",
    "mobile_coverage": "ქვედა ნაწილში.",
    "gear": MULTI_CAMP,
    "tips": ["ტბაში ნუ იბანავებ — ტრიტონების ჰაბიტატია."],
    "sources": "https://nationalparks.ge/en/site/kintrishinp/tripsInner/60",
    "stops": [
      stop("ცხემვანის ვიზიტორთა თავშესაფარი", "start", 41.7600, 42.0470, day=1, alt=400, en="Tskhemvani shelter"),
      stop("ხინოწმინდის ეკლესიის ნანგრევები", "church", 41.7440, 42.1000, day=1, alt=1200, en="Khino church ruins"),
      stop("ტბიყელის ტბა", "lake", 41.7339, 42.1694, day=1, alt=1950, night=True, en="Lake Tbikeli"),
      stop("ცხემვანი", "finish", 41.7600, 42.0470, day=2, alt=400, en="Tskhemvani"),
    ],
  },
  # ───────────── Guria ─────────────
  {
    "slug": "bakhmaro-black-sea",
    "name": "ბახმარო – შავი ზღვა",
    "name_en": "Bakhmaro to the Black Sea coast",
    "region_id": "guria",
    "difficulty": "hard",
    "days_min": 4, "days_max": 5,
    "distance_km": 60, "elevation_gain_m": 4450, "elevation_loss_m": 5040,
    "max_altitude_m": 2600, "min_altitude_m": 200,
    "route_type": "one_way",
    "season_months": [6, 7, 8, 9],
    "tags": ["forest", "views", "camping", "huts", "national_park"],
    "summary": "მთიდან ზღვამდე: ბახმაროს ალპური მდელოებიდან მესხეთის ქედით და კინტრიშის ეროვნული პარკით შავი ზღვის სანაპირომდე.",
    "description": (
      "პირველ დღეს ბახმაროდან ალპურ მდელოებზე ადიხარ, მეორე დღეს — ქედით ჯვარიმინდორის თავშესაფრებამდე. შემდეგ კინტრიშის ეროვნული პარკის ტყეებით "
      "ჩადიხარ ზღვისკენ (ჩახათი, ქობულეთი). ბოლო დღეები ნოტიო და ცხელია ხეობებში."
    ),
    "difficulty_notes": "4–5 გრძელი დღე, ჯამში ~4 500 მ აღმართი და ~5 000 მ დაღმართი; ცხელი, მტვრიანი და ნოტიო მონაკვეთები.",
    "getting_there": "ბახმარომდე პირდაპირი მარშრუტკა იშვიათია — ბათუმის მიმართულების ავტობუსით საჯავახოს წრემდე, იქიდან ჩოხატაურის გავლით მანქანით.",
    "accommodation": "კარავი; მერია კელზე საოჯახო სასტუმრო, ჯვარიმინდორის თავშესაფრები, ბოლო დღეებში რეინჯერის სადგური/მონასტერი.",
    "water": "დღეში ერთხელ მაინც შევსების შესაძლებლობაა.",
    "permits": "კინტრიშის პარკისთვის — რეგისტრაცია ადმინისტრაციასთან.",
    "dangers": "სიცხე და მტვერი მეორე დღეს, ზვავის საფრთხე ზამთარში, მდინარეები.",
    "mobile_coverage": "ქედზე ნაწილობრივ.",
    "gear": MULTI_CAMP,
    "tips": ["ბახმაროში ერთი ღამე გაატარე აკლიმატიზაციისთვის და მზის ჩასვლის სანახავად."],
    "sources": "https://www.caucasus-trekking.com/treks/trek-from-bakhmaro-to-coast",
    "stops": [
      stop("ბახმარო", "start", 41.8517, 42.3172, day=1, alt=2000, en="Bakhmaro"),
      stop("ალპური მდელო (ბანაკი)", "camp", 41.8180, 42.2400, day=1, alt=2400, night=True, en="Alpine meadow camp"),
      stop("ჯვარიმინდორის თავშესაფრები", "hut", 41.7560, 42.1820, day=2, alt=2100, night=True, en="Jvarimindori shelters"),
      stop("კინტრიშის გზაჯვარედინი", "camp", 41.7650, 42.0650, day=3, alt=600, night=True, en="Kintrishi crossroad"),
      stop("ჩახათი", "finish", 41.8000, 41.8700, day=5, alt=200, en="Chakhati"),
    ],
  },
]
